Algoritmo "Entrada e saida de dados"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Savio Lima
// Data atual  : 18/10/2020
Var
// Seção de Declarações das variáveis 
// Primeiro Nome
// Segundo Nome
// Idade
// Cidade
// Endereco


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo